---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4 
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    customize:
      cpus: 1 
      memory: 1024

- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9 
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
    customize:
      cpus: 1 
      memory: 1024

- name: CentOS-LXC-6.4
  driver_config:
    provider: lxc
    box: vagrant-lxc-CentOS-6.4-x86_64-ja
    box_url: https://dl.dropboxusercontent.com/u/428597/vagrant_boxes/vagrant-lxc-CentOS-6.4-x86_64-ja.box

suites:
- name: default
  run_list: 
    - "recipe[trac::default]"
  attributes: {}
